name: eco_conscience
description: A 2D pixel art video game built using Flutter and Flame where your choices matter and transform the world!
publish_to: 'none'

version: 1.0.2+4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.16.0
  flame_tiled: ^1.19.0
  flame_tiled_utils: ^1.1.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  provider: ^6.1.1
  flame_audio: ^2.1.8
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2
  firebase_core: ^3.5.0
  firebase_analytics: ^11.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/HUD/Earth.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/HUD/Earth.png"
  macos:
    generate: true
    image_path: "assets/images/HUD/Earth.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/tiles/
    - assets/tiles/tileSets/
    - assets/images/Characters/
    - assets/images/HUD/
    - assets/images/Interiors/
    - assets/images/Exteriors/
    - assets/images/Exteriors/skyline/
    - assets/images/Lessons/
    - assets/google_fonts/
    - assets/audio/
    - assets/google_buttons/

  fonts:
    - family: Arcade-In
      fonts:
        - asset: assets/fonts/8-bit Arcade In.ttf

    - family: Arcade-Out
      fonts:
        - asset: assets/fonts/8-bit Arcade Out.ttf

    - family: 4B30
      fonts:
        - asset: assets/fonts/04B_30__.TTF

    - family: VT323
      fonts:
        - asset: assets/google_fonts/VT323-Regular.ttf

    - family: Jackey
      fonts:
        - asset: assets/fonts/jackeyfont.ttf
