// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5KoeUsc16V1Mz7nIcf5FTHQ3uVIizEL8',
    appId: '1:85722245468:web:b3f56cb67150db122b3999',
    messagingSenderId: '85722245468',
    projectId: 'ecoshift-chronicles-f4b79',
    authDomain: 'ecoshift-chronicles-f4b79.firebaseapp.com',
    storageBucket: 'ecoshift-chronicles-f4b79.appspot.com',
    measurementId: 'G-BC5X9GB9WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDBzp7kUkNW3Pu8SQICt2v5ITt9-WjQpw',
    appId: '1:85722245468:android:baa25ce411badaed2b3999',
    messagingSenderId: '85722245468',
    projectId: 'ecoshift-chronicles-f4b79',
    storageBucket: 'ecoshift-chronicles-f4b79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsaZy4NbeC8Xb6bCjgYaufJNzD5_RwMHg',
    appId: '1:85722245468:ios:e34649c37678a2d92b3999',
    messagingSenderId: '85722245468',
    projectId: 'ecoshift-chronicles-f4b79',
    storageBucket: 'ecoshift-chronicles-f4b79.appspot.com',
    iosBundleId: 'com.example.ecoConscience',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsaZy4NbeC8Xb6bCjgYaufJNzD5_RwMHg',
    appId: '1:85722245468:ios:e34649c37678a2d92b3999',
    messagingSenderId: '85722245468',
    projectId: 'ecoshift-chronicles-f4b79',
    storageBucket: 'ecoshift-chronicles-f4b79.appspot.com',
    iosBundleId: 'com.example.ecoConscience',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5KoeUsc16V1Mz7nIcf5FTHQ3uVIizEL8',
    appId: '1:85722245468:web:a279d1bd6b0e798b2b3999',
    messagingSenderId: '85722245468',
    projectId: 'ecoshift-chronicles-f4b79',
    authDomain: 'ecoshift-chronicles-f4b79.firebaseapp.com',
    storageBucket: 'ecoshift-chronicles-f4b79.appspot.com',
    measurementId: 'G-6G8D7CKRNJ',
  );
}
